See changelog 20200731-1.2.3

diff --git a/src/bigtime b/src/bigtime
--- a/src/bigtime
+++ b/src/bigtime
@@ -10,7 +10,7 @@
 
 progname="$(basename "$0")"
 PROGNAME="${progname^^}"
-VERSION="20200730-1.2.2"
+VERSION="20200731-1.2.3"
 
 CONFIG_PATH="/etc/bigtime"
 DIGITS_PATH="$CONFIG_PATH/digits"
@@ -45,59 +45,74 @@ RBC=(39 38 44 43 49 48 84 83 119 118 154 148 184 178 214 208 209 203 204 198 199
 declare -i CLOCKH
 declare -i CLOCKW
 
-PRESETS=("█" " " "▮" " " "⦁" " " "◆" " " "▓" " " "♥" " " "⏺" " ")
-
 __help() {
 
 cat << 'EOB' >&2
 BIGTIME - customizable digital clock
 
 USAGE:
-bigtime [OPTION VALUE ... OPTION VALUE]
+bigtime [OPTION [VALUE] ... OPTION [VALUE]]
 
 OPTIONS:
--c, --char "CHAR"     - character for digits (default is "∎").
--p, --space "CHAR"    - character for whitespaces (default is " ").
--f                    - display time in 24h format.
--s, --small-seconds   - show seconds (normal size).
--S, --big-seconds     - show seconds (big size).
--d, --date            - show date.
--z, --timezone        - show timezone (i.e. +0200).
--F, --foreground 0..N - set foreground color (override -n and -r options).
--B, --background 0..N - set background color.
--r, --rainbow         - rainbow effect.
--n, --random          - random colors effect.
--C, --list-colors     - print available colors and exit.
--b, --blink           - blinking separators.
--v, --vertical        - display clock vertically.
--a, --alarm TIME      - set alarm.
--i, --signal          - hourly time signal.
--t, --timer DURATION  - set timer (format: [H]H:MM[:SS]).
---file FILENAME       - use a custom digits file (filename only)
--l, --list-files      - print available digits files and exit.
---preset 0..N         - use predefined characters (override -c and -p options).
--P, --list-presets    - print preset characters.
--h, --help            - print this help message and exit
--V, --version         - print program version info and exit.
+    -s, --small-seconds
+        Show seconds (normal size).
+    -S, --big-seconds
+        Show seconds (big size).
+    -d, --date
+        Show date.
+    -f
+        Display time in 24h format.
+    -z, --timezone
+        Show timezone (i.e. +0200).
+    -F, --foreground 0..N
+        Set foreground color (override -n and -r options).
+    -B, --background 0..N
+        Set background color.
+    -r, --rainbow
+        Rainbow effect.
+    -n, --random
+        Random colors effect.
+    -C, --list-colors
+        Print available colors and exit.
+    -b, --blink
+        Blinking separators.
+    -v, --vertical
+        Display clock vertically.
+    -a, --alarm [H]H:MM[AM|am|PM|pm]
+        Set daily alarm.
+    -i, --signal
+        Hourly time signal.
+    -t, --timer [H]:MM[:SS]
+        Set timer.
+    --fiLe FILENAME
+        Use a custom digits file (filename only)
+    -w, --preview
+        Display a preview of --file and exit.
+    -l, --list-files
+        Print available digits files and exit.
+    -h, --help
+        Print this help message and exit
+    -V, --version
+        Print program version info and exit.
 
 KEYS BINDINGS:
-a                     - toggle/set daily alarm; confirm (alarm setting mode)
-h                     - toggle hourly time signal
-j                     - select next digit (alarm/timer setting mode)
-k                     - select previous digit (alarm/timer setting mode)
-p                     - toggle 24h format; toggle AM/PM (alarm setting mode)
-q                     - exit program
-r                     - reset timer (timer setting mode)
-R                     - refresh screen
-t                     - toggle/set timer; confirm (timer setting mode)
-space                 - toggle display; stop alarm/timer; cancel (alarm/timer setting mode)
+    a     - toggle/set daily alarm; confirm (alarm setting mode)
+    h     - toggle hourly time signal
+    j     - select next digit (alarm/timer setting mode)
+    k     - select previous digit (alarm/timer setting mode)
+    p     - toggle 24h format; toggle AM/PM (alarm setting mode)
+    q     - exit program
+    r     - reset timer (timer setting mode)
+    R     - refresh screen
+    t     - toggle/set timer; confirm (timer setting mode)
+    space - toggle display; stop alarm/timer; cancel (alarm/timer setting mode)
 
 EOB
 }
 
 __err() { ( >&2 echo -e "$progname: $1" ) }
 
-which tput > /dev/null || { __err "it will not work without ncurses"; exit 1; } 
+which tput > /dev/null || { __err "sorry, it will not work without ncurses"; exit 1; } 
 
 # compute clock size
 CLOCK_SIZE() {
@@ -164,32 +179,29 @@ LIST_COLORS() {
 
 # options
 
-_opts=$(LC_ALL=C getopt                   \
-  --long "help"                           \
-  --long "version"                        \
-  --long "preset:"                        \
-  --long "list-presets"                   \
-  --long "char:"                          \
-  --long "space:"                         \
-  --long "small-seconds"                  \
-  --long "big-seconds"                    \
-  --long "date"                           \
-  --long "blink"                          \
-  --long "vertical"                       \
-  --long "alarm:"                         \
-  --long "signal"                         \
-  --long "timer:"                         \
-  --long "file:"                          \
-  --long "list-files"                     \
-  --long "foreground:"                    \
-  --long "background:"                    \
-  --long "list-colors"                    \
-  --long "rainbow"                        \
-  --long "random"                         \
-  --long "timezone"                       \
-  --options "hVc:p:fsSdbva:it:F:B:PClrnz" \
-  --name "$progname"                      \
-  -- "$@"                                 \
+_opts=$(LC_ALL=C getopt              \
+  --long "alarm:"                    \
+  --long "background:"               \
+  --long "big-seconds"               \
+  --long "blink"                     \
+  --long "date"                      \
+  --long "file:"                     \
+  --long "foreground:"               \
+  --long "help"                      \
+  --long "list-colors"               \
+  --long "list-files"                \
+  --long "preview"                   \
+  --long "version"                   \
+  --long "rainbow"                   \
+  --long "random"                    \
+  --long "signal"                    \
+  --long "small-seconds"             \
+  --long "timer:"                    \
+  --long "timezone"                  \
+  --long "vertical"                  \
+  --options "a:B:SbdfF:hCwVrnist:zv" \
+  --name "$progname"                 \
+  -- "$@"                            \
 ) || exit 1
 
 eval set -- "$_opts"
@@ -214,30 +226,6 @@ while :; do
     -n | --random       ) _RC=1; unset _RB _FG; shift ;;
     -C | --list-colors  ) LIST_COLORS; exit 0 ;;
 
-    -c | --char)
-      shift
-      if [[ ! $1 =~ [[:alnum:]] ]]; then
-        __err "error: --char should be alphanumeric"
-        exit 1
-      elif [[ ${#1} != 1 ]]; then
-        __err "error: --char should be 1 character"
-        exit 1
-      fi
-      _CHR="$1"
-      shift
-      ;;
-    -p | --space)
-      shift
-      if [[ ! $1 =~ [[:alnum:]] ]]; then
-        __err "error: --space should be alphanumeric"
-        exit 1
-      elif [[ ${#1} != 1 ]]; then
-        __err "error: --space should be 1 character"
-        exit 1
-      fi
-      _SPC="$1"
-      shift
-      ;;
     --file)
       shift
       [[ $1 =~ \.digits$ ]] && _FILE="$1" || _FILE="$1.digits"
@@ -258,28 +246,10 @@ while :; do
       echo -e "$files"
       exit 0
       ;;
-    --preset)
+    -w | --preview)
+      [[ ! $_FILE ]] && { __err "error: --preview: missing --file option"; exit 1; }
       shift
-      ((plen=(${#PRESETS[@]}-1)/2))
-      if [[ $1 =~ [0-$plen] && $1 -ge 0 && $1 -le $plen ]]; then
-        index=$1
-        _CHR="${PRESETS[$((index*2))]}"
-        _SPC="${PRESETS[$((index*2+1))]}"
-        unset index
-        shift
-      else
-        __err "error: --preset should be a numeric value between 0 and $plen"
-        exit 1
-      fi
-      unset plen
-      ;;
-    -P | --list-presets)
-      j=0
-      for ((i=1;i<${#PRESETS[@]};((i+=2)))); do
-        echo "$j: '${PRESETS[$((i-1))]}' '${PRESETS[$i]}'"
-        ((j++))
-      done
-      exit 0
+      _PV=1
       ;;
     -F | --foreground)
       shift
@@ -294,6 +264,7 @@ while :; do
         __err "error: --foreground should be a numeric value between 0 and $((COLORS-1))"
         exit 1
       fi
+      unset _RB _RC
       shift
       ;;
     -B | --background)
@@ -329,8 +300,9 @@ _FILE="${_FILE:-$DIGITS_DEFAULT_FILE}"
 read_option() {
   local file option
   file="$_FILE"
+  option="$1"
   while read -r line; do
-    if [[ $line =~ ^$1=.*$ ]]; then
+    if [[ $line =~ ^$option=.*$ ]]; then
       IFS=$'\n' read -d "" -ra array <<< "${line//=/$'\n'}"
       if [[ ! ${array[1]} ]]; then
         echo "null"
@@ -351,18 +323,45 @@ SW="$(read_option "sep_width")" || { __err "error: $_FILE: missing 'sep_width' v
 
 CLOCK_SIZE || { __err "error: clock doesn't fit"; exit 1; }
 
-_SPC="${_SPC:-" "}"
-_CHR="${_CHR:-"∎"}"
+_chr="$(read_option "char")"
+if [[ $_chr == "null" ]]; then
+  _CHR="∎"
+  unset _chr
+elif [[ ${#_chr} -ne 1 ]]; then
+  __err "error: $_FILE: 'char' should be 1 character"
+  exit 1
+elif [[ $_chr =~ \\[abcdefnrtv] ]]; then
+  __err "error: $_FILE: 'char' cannot be a backslash escaped character"
+  exit 1
+elif [[ $_chr ]]; then
+  _CHR="$_chr"
+  unset _chr
+fi
+
+_spc="$(read_option "space")"
+if [[ $_spc == "null" ]]; then
+  _SPC=" "
+  unset _spc
+elif [[ ${#_spc} -ne 1 ]]; then
+  __err "error: $_FILE: 'space' should be 1 character"
+  exit 1
+elif [[ $_spc =~ \\[abcdefnrtv] ]]; then
+  __err "error: $_FILE: 'space' cannot be a backslash escaped character"
+  exit 1
+elif [[ $_spc ]]; then
+  _SPC="$_spc"
+  unset _spc
+fi
 
 ### DIGITS
 ### dynamically declare an array for each digit (_D1, _D1... _D9)
-### where 1s are replaced par _CHR and 0s by _SPC
+### where 1s are replaced by _CHR and 0s by _SPC
 for ((i=0;i<10;i++)); do
-  digit="$(read_option "$i")" || { __err "error: $_FILE: digit $i is missing"; return 1; }
+  digit="$(read_option "$i")" || { __err "error: $_FILE: digit $i is missing"; exit 1; }
   IFS=$'\n' read -d "" -ra digit <<< "${digit//$';'/$'\n'}"
-  ((${#digit[@]}!=DH)) && { __err "error: $_FILE: digit $i, height mismatch"; return 1; }
+  ((${#digit[@]}!=DH)) && { __err "error: $_FILE: digit $i, height not equal to $DH"; exit 1; }
   for ((j=0;j<DH;j++)); do
-    ((${#digit[$j]}!=DW)) && { __err "error: $_FILE: digit $i, width mismatch"; return 1; }
+    ((${#digit[$j]}!=DW)) && { __err "error: $_FILE: digit $i, width not equal to $DW"; exit 1; }
     digit[$j]=${digit[$j]//0/"$_SPC"}
     digit[$j]=${digit[$j]//1/"$_CHR"}
     declare -a "_D$i+=(\"${digit[$j]}\")"
@@ -377,11 +376,11 @@ for option in "${options[@]}"; do
   [[ $opt == "null" ]] && { __err -u "error: $_FILE: missing $option"; exit 1; }
   IFS=$'\n' read -d "" -ra opt <<< "${opt//$';'/$'\n'}"
   # check whether height matches declared one
-  ((${#opt[@]}!=DH)) && { __err -u "error: $option: height mismatch"; exit 1; }
+  ((${#opt[@]}!=DH)) && { __err -u "error: $option: height not equal to $DH"; exit 1; }
   # replace 0s and 1s
   for ((i=0;i<DH;i++)); do
     # check whether width matches declared one
-    ((${#opt[$i]}!=SW)) &&{ __err -u "error: $option: width mismatch: col $((i+1))"; exit 1; }
+    ((${#opt[$i]}!=SW)) &&{ __err -u "error: $option: width not equal to $SW: col $((i+1))"; exit 1; }
     opt[$i]=${opt[$i]//0/"$_SPC"}
     opt[$i]=${opt[$i]//1/"$_CHR"}
     case "$option" in
@@ -456,6 +455,31 @@ print_rainbow() {
     done
 }
 
+PREVIEW_FILE() {
+  local __y __x
+  # get cursor position
+  # neat solution from <https://unix.stackexchange.com/questions/88296/get-vertical-cursor-position/183121#183121>
+  # shellcheck disable=SC2162
+  IFS=";" read -sdR -p $'\E[6n' __y __x
+  __y="${__y#*[}"; __x="${__x#*[}"
+  ((__y--))
+  ((__y+DH>TERMH)) && {
+    for ((i=0;i<DH;i++)); do printf $'\n'; done
+    ((__y-=DH))
+  }
+  [[ $_FG ]] && tput setaf "$_FG"
+  [[ $_BG ]] && tput setab "$_BG"
+  print_digit $((__y)) $((__x)) "0"
+  ((__x+=DW+1))
+  print_separator $((__y)) $((__x))
+  ((__x+=SW+1))
+  print_digit $((__y)) $((__x)) "9"
+  [[ $_FG || $_BG ]] && tput sgr0
+  echo
+}
+
+[[ $_PV ]] && { PREVIEW_FILE; exit 0; }
+
 play_sound() {
   which aplay > /dev/null && {
     case "$1" in
@@ -474,14 +498,17 @@ play_sound() {
 
 set_alarm() {
   [[ $_AA ]] && {
-    local fm="^[0-2][0-3]:[0-5][0-9]:[0-5][0-9]$"
-    local am="^[0-2][0-2]:[0-5][0-9]:[0-5][0-9] (AM|PM)$"
-    if [[ $_FM ]] && [[ ! $_AT =~ $fm ]]; then
+    [[ $1 == "cmdline" ]] && {
+      [[ $_AT == "now" ]] && { AR=1; unset _AA _AT; return 0; }
+      local fm="^[0-2]?[0-9]:[0-5][0-9][[:space:]]?(AM|am|PM|pm)?$"
+      [[ ! $_AT =~ $fm ]] && return 1
+    }
+    if [[ $_FM ]]; then
       _AT="$(date -d "$_AT" "+%H:%M:%S" 2> /dev/null )" || {
         play_sound error
         return 1
       }
-    elif [[ ! $_FM ]] && [[ ! $_AT =~ $am ]]; then
+    else
       _AT="$(LC_TIME=C date -d "$_AT" "+%I:%M:%S %p" 2> /dev/null)" || {
         play_sound error
         return 1
@@ -493,7 +520,6 @@ set_alarm() {
     unset _T
     return 0
   }
-  return 1
 }
 
 set_timer() {
@@ -531,7 +557,7 @@ to_hms() {
   printf "%02d:  :%02d:%02d:%02d:%s:%s:%s:%s" "$H" "$H" "$M" "$S" "$(date "+%s")" "$W" "$D" "$m"
 }
 
-if [[ $_AA ]]; then set_alarm || { __err "error: invalid alarm time"; exit 1; }; fi
+if [[ $_AA ]]; then set_alarm cmdline || { __err "error: invalid alarm time"; exit 1; }; fi
 if [[ $_AA ]]; then AT=$__AT; unset __AT; fi
 if [[ $_TA ]]; then set_timer || { __err "error: invalid timer duration"; exit 1; }; fi
 if [[ $_TT ]]; then activate_timer || EXIT_CLOCK "what ?"; fi
@@ -563,7 +589,7 @@ DISPLAY_ALARM() {
 
 DISPLAY_TIMER() {
   [[ $_TD || $_TS ]] && {
-      local T H M S # d d_array
+      local T H M S d d_array
       IFS=$'\n' read -d "" -ra T <<< "${_TT//:/$'\n'}"
       H="${T[0]}"
       M="${T[1]}"
@@ -696,6 +722,7 @@ TOGGLE_SELECTION() {
   [[ $_HD && $_TA ]] && { play_sound key; _TD=1; _hd=1; unset _HD IT S1 S2; return 0; }
   [[ $_AD ]] && { play_sound key; _HD=1; unset _AD _GD IA IZ PB _hd OT; erase_hd; return 0; }
   [[ $_TD ]] && { play_sound key; _HD=1; unset _TD _GD IT IZ _hd OT; erase_hd; return 0; }
+  return 1
 }
 
 TOGGLE_ALARM() {
@@ -1028,9 +1055,9 @@ while :; do
   s1=${_S:0:1}
   s2=${_S:1:1}
 
-  [[ $AR && $RA -gt 60 ]] && { unset AR RA IA; AZ=1; }
+  [[ $AR && $RA -gt 60 ]] && { unset AR RA IA; }
   [[ $TR && $RA -gt 15 ]] && { unset TR RA _TA _TD IT IZ; _HD=1; }
-  [[ $AZ ]] && { ((AZ==300)) && { AR=1; RA=0; unset IA AZ; }; }
+  [[ $AZ ]] && { ((AZ==300)) && { AR=1; RA=0; AZ=1; unset IA; }; }
 
   # alarm
   [[ $_AA && ! $_AD && ! $_AS ]] && [[ $AT == "$_s" ]] && {
@@ -1041,6 +1068,7 @@ while :; do
     # set new alarm for tomorrow
     ((AT+=86400))
     AR=1
+    AZ=1
     RA=0
     unset IA
   } 
@@ -1075,6 +1103,8 @@ while :; do
           echo ">a " | print_rainbow
         elif [[ $_AS ]]; then
           echo " a>" | print_rainbow
+        elif [[ $AZ ]]; then
+          echo "Zzz"
         else
           echo " a " | print_rainbow
         fi
